//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotek
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BibliotekDbEntities1 : DbContext
    {
        public BibliotekDbEntities1()
            : base("name=BibliotekDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bok> Boks { get; set; }
        public virtual DbSet<Forfattare> Forfattares { get; set; }
        public virtual DbSet<Kopia> Kopias { get; set; }
        public virtual DbSet<Kund> Kunds { get; set; }
        public virtual DbSet<Lan> Lans { get; set; }
        public virtual DbSet<vAntalKopiorTillgangligaUtlaning> vAntalKopiorTillgangligaUtlanings { get; set; }
        public virtual DbSet<vUtlanadAvKundOchVaraTillbaka> vUtlanadAvKundOchVaraTillbakas { get; set; }
    
        public virtual int Tillbakalamning(Nullable<int> kopiaId)
        {
            var kopiaIdParameter = kopiaId.HasValue ?
                new ObjectParameter("KopiaId", kopiaId) :
                new ObjectParameter("KopiaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tillbakalamning", kopiaIdParameter);
        }
    
        public virtual int Utlaning(Nullable<int> kundId, Nullable<int> kopiaId)
        {
            var kundIdParameter = kundId.HasValue ?
                new ObjectParameter("KundId", kundId) :
                new ObjectParameter("KundId", typeof(int));
    
            var kopiaIdParameter = kopiaId.HasValue ?
                new ObjectParameter("KopiaId", kopiaId) :
                new ObjectParameter("KopiaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Utlaning", kundIdParameter, kopiaIdParameter);
        }
    
        public virtual int DeleteKund(Nullable<int> kundId)
        {
            var kundIdParameter = kundId.HasValue ?
                new ObjectParameter("KundId", kundId) :
                new ObjectParameter("KundId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteKund", kundIdParameter);
        }
    }
}
